### ISSUE TITLE
Unique validator - TypeError: docs.filter is not a function

### ISSUE THREAD

**Issue by alzab** [BenZed/feathers-schema#4]
Unfortunately using a 'unique' validator doesn't seem to work for me. When trying to validate a model on creation, where the email field is set to unique (using Knex db backend), I get:

```
error:  TypeError: docs.filter is not a function
     at Property._callee2$ (/app/node_modules/feathers-schema/lib/validators/general.js:209:27)
     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:65:40)
     at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:299:22)
     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:117:21)
     at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
     at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
     at <anonymous>
```

My guess is docs is not an array for whatever reason. Any ideas why?
Thanks!

**Comment by BenZed** [comment]
What a coincidence, I literally just found this problem for myself, yesterday.

The long and short of it is that *feathers-schema* doesn't correctly account for bulk queries. I am working on a fix as we speak!

**Comment by BenZed** [comment]
@alzab, *feathers-schema@0.2.1* should fix this issue, it's passing my written tests.

Let me know if it works for you, and if not we'll investigate further!

**Comment by alzab** [comment]
@BenZed Thanks for this - unfortunately I'm still seeing this issue for some reason! I'm not performing a bulk query, just a regular create. 

Here's how I defined the schema:
```
export const userSchemaProps = {
  email: { type: String, required: true, email: true, unique: true },
  password: { type: String, required: true, length: { min: 2, max: 50 } },
  firstName: { type: String, required: true, length: { min: 1, max: 100 } },
  lastName: { type: String, required: true, length: { min: 1, max: 100 } },
  phoneNumber: { type: String, required: true, length: { min: 6, max: 15 } }
}

export const userSchema = new Schema(userSchemaProps);
```
It's just a simple `create` triggering the issue:
```
hook.app.service('users').create({
    email: email,
    password: password,
    firstName: firstName,
    lastName: lastName,
    phoneNumber: phoneNumber
})
...
```
Bit of a strange one!

**Comment by BenZed** [comment]
I wasn't able to reproduce the problem with your schema, can you show me anything deeper?

It looks like you're creating a user from inside of a hook. What's the nature of the hook?
Are there any other *before* hooks that manipulate `hook.data` in the *users* service?
What is the value of the *email* field when you create that user?

If possible, let me take a look at the repo!

**Comment by alzab** [comment]
I think I located the issue based on your advise to log at those lines. Here's what I got in the logs:
```
{ total: 0, limit: 10, skip: 0, data: [] }
{ total: 0, limit: 10, skip: 0, data: [] }
```
The issue appears to be pagination settings - if they aren't set, then that structure above is collapsed to `data`. So it seems there's a number of possible cases that need to be handled, or perhaps Feathers provides a more elegant solution in some form?

**Comment by BenZed** [comment]
Yup, I'd say you're correct.

*feathers-schema* isn't taking service pagination configuration into account when it makes find() calls.

I'll fix this *asap*

**Comment by BenZed** [comment]
@alzab, update *feathers-schema@0.2.2*, I've fixed this issue!

**Comment by alzab** [comment]
@BenZed awesome! Thanks a lot!
